# Welcome to numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]],np.int8)

In [3]:
myarr

array([[ 3,  6, 32,  7]], dtype=int8)

In [4]:
myar = np.array([1,2,3])

In [5]:
myar

array([1, 2, 3])

In [6]:
myarr[0][1]

6

In [7]:
myarr.shape

(1, 4)

In [8]:
myarr.dtype

dtype('int8')

In [9]:
myarr[0,1]=544

C:\Users\SUDESH KUMAR\AppData\Local\Temp\ipykernel_11780\3888302816.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 544 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  myarr[0,1]=544


In [10]:
myarr

array([[ 3, 32, 32,  7]], dtype=int8)

In [11]:
myarr[0][1]=54

In [12]:
myarr

array([[ 3, 54, 32,  7]], dtype=int8)

In [13]:
myarr[0,1]

54

In [14]:
myarr[0,1]=100

In [15]:
myarr

array([[  3, 100,  32,   7]], dtype=int8)

In [16]:
myarr.size

4

**Array creation : Conversion from other python structures**

In [17]:
listarray = np.array([[1,2,3],[4,5,6],[0,3,1]])

In [18]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [0, 3, 1]])

In [19]:
listarray.dtype

dtype('int32')

In [20]:
listarray.shape

(3, 3)

In [21]:
listarray.size

9

In [22]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [23]:
zeros = np.zeros((2,5))

In [24]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
zeros.shape

(2, 5)

In [26]:
rng = np.arange(15)

In [27]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
lspace = np.linspace(1,4,6)

In [29]:
lspace

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [30]:
emp = np.empty((4,5))

In [31]:
emp

array([[1.49776096e-311, 6.22522714e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.15998412e-028, 4.31603868e-080, 1.94919985e-153,
        1.35717430e+131, 7.06652016e-096],
       [7.06652016e-096, 1.81148490e-152, 9.37041222e-076,
        6.98345624e-077, 6.98345624e-077],
       [1.06239598e-153, 3.98472821e+252, 1.06244660e-153,
        9.78750380e+199, 6.97843734e+252]])

In [32]:
emp_like = np.empty_like(lspace)

In [33]:
emp_like

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [34]:
lspace

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [35]:
ide = np.identity(45)

In [36]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [37]:
ide.shape

(45, 45)

In [38]:
arr = np.arange(99)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

**Numpy axis**

In [45]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [46]:
ar = np.array(x)

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar.sum(axis=0)

array([12,  8,  9])

In [49]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [66]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [68]:
ar.flat

In [69]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [71]:
one = np.array([1,3,4,634,2])


In [73]:
one.argmin()

0

In [74]:
one.argmax()

3

In [75]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [76]:
ar.argmin()

8

In [81]:
ar.argmax()

6

In [82]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [83]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [78]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [80]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [84]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

**Mathematical Calculations**

In [86]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [87]:
ar2 = np.array([[1,2,1],
                [4,0,6],
                [8,1,0]])

In [88]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [89]:
ar - ar2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [90]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [91]:
ar / ar2

C:\Users\SUDESH KUMAR\AppData\Local\Temp\ipykernel_11780\33319274.py:1: RuntimeWarning: divide by zero encountered in divide
  ar / ar2
C:\Users\SUDESH KUMAR\AppData\Local\Temp\ipykernel_11780\33319274.py:1: RuntimeWarning: invalid value encountered in divide
  ar / ar2


array([[1.   , 1.   , 3.   ],
       [1.   ,   inf, 1.   ],
       [0.875, 1.   ,   nan]])

In [92]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [94]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [95]:
type(np.where(ar>5))

tuple

In [97]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

**How numpy takes less space**

In [99]:
import sys

In [100]:
py_ar = [0,4,55,2]

In [101]:
np_ar = np.array(py_ar)

In [102]:
sys.getsizeof(1)*len(py_ar)

112

In [104]:
np_ar.itemsize * np_ar.size

16